const commonProducts = [
  { key: 'milk', matchKeywords: ['milk', 'taaza', 'amul milk', 'cow milk', 'toned milk', 'double toned milk', 'skimmed milk'] },
  { key: 'paneer', matchKeywords: ['paneer', 'cottage cheese', 'amul paneer', 'fresh paneer'] },
  { key: 'curd', matchKeywords: ['curd', 'dahi', 'plain curd', 'thick curd'] },
  { key: 'butter', matchKeywords: ['butter', 'amul butter', 'white butter', 'salted butter', 'unsalted butter'] },
  { key: 'cheese', matchKeywords: ['cheese', 'cheddar', 'mozzarella', 'processed cheese', 'sliced cheese'] },
  { key: 'ghee', matchKeywords: ['ghee', 'clarified butter', 'cow ghee', 'amul ghee'] },
  { key: 'yogurt', matchKeywords: ['yogurt', 'greek yogurt', 'flavored yogurt', 'fruit yogurt'] },
  { key: 'eggs', matchKeywords: ['egg', 'eggs', 'white eggs', 'brown eggs', 'country egg'] },
  { key: 'meat', matchKeywords: ['meat', 'chicken', 'mutton', 'fish', 'keema', 'meatballs', 'prawns', 'seafood', 'boneless chicken'] },
  { key: 'fruits', matchKeywords: ['fruit', 'fruits', 'apple', 'banana', 'mango', 'orange', 'grape', 'papaya', 'kiwi', 'pineapple', 'melon', 'watermelon', 'berries'] },
  { key: 'vegetables', matchKeywords: ['vegetable', 'vegetables', 'onion', 'tomato', 'potato', 'carrot', 'peas', 'cabbage', 'spinach', 'capsicum', 'okra', 'beetroot', 'garlic', 'ginger'] },
  { key: 'atta', matchKeywords: ['atta', 'wheat flour', 'whole wheat', 'chakki atta', 'multigrain atta'] },
  { key: 'rice', matchKeywords: ['rice', 'basmati', 'sona masoori', 'kolam rice', 'boiled rice'] },
  { key: 'dal', matchKeywords: ['dal', 'lentils', 'toor', 'moong', 'chana dal', 'masoor dal', 'urad dal'] },
  { key: 'oil', matchKeywords: ['oil', 'mustard oil', 'sunflower oil', 'coconut oil', 'olive oil', 'refined oil', 'groundnut oil'] },
  { key: 'salt', matchKeywords: ['salt', 'rock salt', 'sendha namak', 'table salt', 'iodized salt'] },
  { key: 'sugar', matchKeywords: ['sugar', 'brown sugar', 'white sugar', 'powdered sugar', 'jaggery', 'gur'] },
  { key: 'masala', matchKeywords: ['masala', 'spices', 'haldi', 'turmeric', 'jeera', 'coriander powder', 'garam masala', 'chilli powder'] },
  { key: 'tea', matchKeywords: ['tea', 'chai', 'green tea', 'black tea', 'masala tea'] },
  { key: 'coffee', matchKeywords: ['coffee', 'instant coffee', 'filter coffee', 'brew'] },
  { key: 'jam', matchKeywords: ['jam', 'fruit spread', 'strawberry jam', 'mixed fruit jam'] },
  { key: 'pickle', matchKeywords: ['pickle', 'achaar', 'mango pickle', 'lime pickle'] },
  { key: 'snacks', matchKeywords: ['snack', 'namkeen', 'chips', 'kurkure', 'mixture', 'murukku'] },
  { key: 'biscuits', matchKeywords: ['biscuit', 'cookies', 'oreo', 'parle', 'good day'] },
  { key: 'chocolate', matchKeywords: ['chocolate', 'dark chocolate', 'milk chocolate', 'cadbury', 'ferrero'] },
  { key: 'noodles', matchKeywords: ['noodles', 'maggi', 'instant noodles', 'ramen'] },
  { key: 'beverages', matchKeywords: ['drink', 'cola', 'juice', 'energy drink', 'soft drink', 'soda', 'sprite', 'pepsi', 'fruit juice', 'tetra pack'] },
];

export default commonProducts;
